from . import account_move
from . import elinvoice_confirmation
from . import res_company
from . import res_partner
from . import elinvoice_configuration
from . import elinvoice_country
from . import elinvoice_state
from . import elinvoice_city
from . import elinvoice_economic_activity
from . import product_template
from . import account_move_line
from . import stock_picking
from . import sale_order
from . import account_payment_term